name: Build and deploy ASP app to Azure Web App - asfdatabase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: List files for debugging
        run: dir /s /b
        shell: cmd

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Adjust the .NET version if necessary

      - name: Restore NuGet packages
        run: dotnet restore ASFDatabase-main/ASFDatabase.csproj # Use the project file here

      - name: Publish to folder
        run: dotnet publish ASFDatabase-main/ASFDatabase.csproj -c Release -o published # Use the project file here

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: ASP-app
          path: 'published/**'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ASP-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_674B09814AEA4DDBB2CAC8EF84D36E96 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_180998D94E314CA3980558563563EF42 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3AE58435BF5843FC881DAD7CA2747C76 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'asfdatabase'
          slot-name: 'Production'
          package: .

